---
bug:
  - '\[BUG\]'

feedback:
  - '\[FEED\]'

role:server:
  - '/component name:.*server.*$/i'
  - 'Component Name:.*server.*$'
  - '/component name: server/i'
  - 'Component Name: server'

role:agent:
  - '/component name:.*agent.*$/i'

module:activation:
  - '/component name:.*activation.*$/i'

module:bakery:
  - '/component name:.*bakery.*$/i'

module:contact_group:
  - '/component name:.*contact_group.*$/i'

module:discovery:
  - '/component name:.*discovery.*$/i'

module:downtime:
  - '/component name:.*downtime.*$/i'

module:folder:
  - '/component name:.*folder.*$/i'

module:host:
  - '/component name:.*host.*$/i'

module:host_group:
  - '/component name:.*host_group.*$/i'

module:password:
  - '/component name:.*password.*$/i'

module:rule:
  - '/component name:.*rule.*$/i'

module:service_group:
  - '/component name:.*service_group.*$/i'

module:tag_group:
  - '/component name:.*tag_group.*$/i'

module:user:
  - '/component name:.*user.*$/i'
