---
bug:
  - '\[BUG\]'

feedback:
  - '\[FEED\]'

role:server:
  - 'Component Name: server'

role:agent:
  - 'Component Name: agent'

inventory:
  - 'Component Name: inventory'

module:activation:
  - 'Component Name: activation'

module:aux_tag:
  - 'Component Name: aux_tag'

module:bakery:
  - 'Component Name: bakery'

module:contact_group:
  - 'Component Name: contact_group'

module:dcd:
  - 'Component Name: dcd'

module:discovery:
  - 'Component Name: discovery'

module:downtime:
  - 'Component Name: downtime'

module:folder:
  - 'Component Name: folder'

module:host:
  - 'Component Name: host'

module:host_group:
  - 'Component Name: host_group'

module:password:
  - 'Component Name: password'

module:rule:
  - 'Component Name: rule'

module:service_group:
  - 'Component Name: service_group'

module:site:
  - 'Component Name: site'

module:tag_group:
  - 'Component Name: tag_group'

module:timeperiod:
  - 'Component Name: timeperiod'

module:user:
  - 'Component Name: user'

lookup:bakery:
  - 'Component Name: lookup_bakery'

lookup:folder:
  - 'Component Name: lookup_folder'
  - 'Component Name: lookup_folders'

lookup:host:
  - 'Component Name: lookup_host'
  - 'Component Name: lookup_hosts'

lookup:ldap_connection:
  - 'Component Name: lookup_ldap_connection'
  - 'Component Name: lookup_ldap_connections'

lookup:rule:
  - 'Component Name: lookup_rule'
  - 'Component Name: lookup_rules'

lookup:ruleset:
  - 'Component Name: lookup_ruleset'
  - 'Component Name: lookup_rulesets'

lookup:site:
  - 'Component Name: lookup_site'
  - 'Component Name: lookup_sites'

lookup:version:
  - 'Component Name: lookup_version'
