---
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['**/*.md', '**/*.rst', 'docs/*', 'changelogs/*']

role:server:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'roles/server/**'

role:agent:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'roles/agent/**'

inventory:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/inventory/checkmk.py'

module:activation:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/activation.py'

module:aux_tag:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/aux_tag.py'

module:bakery:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/bakery.py'

module:bi_aggregation:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/bi_aggregation.py'

module:bi_pack:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/bi_pack.py'

module:bi_rule:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/bi_rule.py'

module:contact_group:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/contact_group.py'

module:dcd:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/dcd.py'

module:dcd_metricbackend:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/dcd_metricbackend.py'

module:discovery:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/discovery.py'

module:downtime:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/downtime.py'

module:folder:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/folder.py'

module:host:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/host.py'

module:host_group:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/host_group.py'

module:ldap:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/ldap.py'

module:metricbackend:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/metricbackend.py'

module:notification:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/notification.py'

module:opentelemetry:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/opentelemetry.py'

module:password:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/password.py'

module:role:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/role.py'

module:rule:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/rule.py'

module:service_group:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/service_group.py'

module:site:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/site.py'

module:tag_group:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/tag_group.py'

module:timeperiod:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/timeperiod.py'

module:user:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/modules/user.py'

lookup:activation:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/activation.py'
          - any-glob-to-any-file: 'plugins/lookup/activations.py'

lookup:bakery:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/bakery.py'

lookup:bi_aggregation:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/bi_aggregation.py'
          - any-glob-to-any-file: 'plugins/lookup/bi_aggregations.py'

lookup:bi_pack:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/bi_pack.py'
          - any-glob-to-any-file: 'plugins/lookup/bi_packs.py'

lookup:bi_rule:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/bi_rule.py'
          - any-glob-to-any-file: 'plugins/lookup/bi_rules.py'

lookup:dcd:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/dcd.py'

lookup:folder:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/folder.py'
          - any-glob-to-any-file: 'plugins/lookup/folders.py'

lookup:host:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/host.py'
          - any-glob-to-any-file: 'plugins/lookup/hosts.py'

lookup:ldap_connection:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/ldap_connection.py'
          - any-glob-to-any-file: 'plugins/lookup/ldap_connections.py'

lookup:role:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/role.py'
          - any-glob-to-any-file: 'plugins/lookup/roles.py'

lookup:rule:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/rule.py'
          - any-glob-to-any-file: 'plugins/lookup/rules.py'

lookup:ruleset:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/ruleset.py'
          - any-glob-to-any-file: 'plugins/lookup/rulesets.py'

lookup:site:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/site.py'
          - any-glob-to-any-file: 'plugins/lookup/sites.py'

lookup:version:
  - any:
      - changed-files:
          - any-glob-to-any-file: 'plugins/lookup/version.py'
