---
__checkmk_agent_site_url: "{{ checkmk_agent_server_protocol }}://{{ checkmk_agent_server }}:{{ checkmk_agent_server_port }}/{{ checkmk_agent_site }}"

__checkmk_agent_auth: |-
  {% if checkmk_agent_secret is defined and checkmk_agent_secret | length > 0 %}{{ checkmk_agent_secret }}{% else %}{{ checkmk_agent_pass }}{% endif %}

# Single source of truth: legacy short codes to current edition identifiers.
__checkmk_var_short_code_mapping:
  cre: community
  cee: pro
  cce: ultimate
  cme: ultimatemt

# Maps current edition identifiers to download URL identifiers for Checkmk < 2.5.
__checkmk_var_legacy_edition_mapping:
  community: raw
  pro: enterprise
  ultimate: cloud
  ultimatemt: managed

# Maps current edition identifiers to download URL identifiers for Checkmk >= 2.5.
__checkmk_var_modern_edition_mapping:
  community: community
  pro: pro
  ultimate: ultimate
  ultimatemt: ultimatemt

# Bringing the above two mappings back together.
__checkmk_agent_edition_mapping: >-
  {{
    ( (checkmk_agent_version | regex_replace('p.*', '')) is version('2.5', '<') )
    | ternary(__checkmk_var_legacy_edition_mapping, __checkmk_var_modern_edition_mapping)
  }}

__checkmk_agent_files_mapping:
  Debian: linux_deb
  RedHat: linux_rpm
  Suse: linux_rpm
  Windows: windows_msi
