---

__checkmk_server_setup_file: |-
  check-mk-{{ __checkmk_server_edition_mapping[checkmk_server_edition | lower] }}-{{ checkmk_server_version }}-el{{ ansible_distribution_major_version }}-38.x86_64.rpm

__checkmk_server_ports:
  - 80/tcp
  - 443/tcp
  - 8000/tcp

__checkmk_server_prerequisites_per_distro:
  RedHat:
    - firewalld
    - dnf-plugins-core
    - python3-libsemanage
  CentOS:
    - firewalld
    - dnf-plugins-core
    - python3-libsemanage
  CentOS-7:
    - firewalld
    - dnf-plugins-core
    - libsemanage-python
  CentOS-8:
    - firewalld
    - dnf-plugins-core
    - python3-libsemanage
  RedHat-7:
    - firewalld
    - libsemanage-python
  RedHat-8:
    - firewalld
    - dnf-plugins-core
    - python3-libsemanage
  OracleLinux-8:
    - firewalld
    - dnf-plugins-core
    - python3-libsemanage

__checkmk_server_prerequisites: "{{ __checkmk_server_prerequisites_per_distro[ansible_facts.distribution ~ '-' ~ ansible_facts.distribution_major_version]
  | default( __checkmk_server_prerequisites_per_distro[ ansible_distribution_file_variety ]) }}"

__checkmk_server_epel_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm"
__checkmk_server_epel_gpg_key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_facts.distribution_major_version }}"
