---

- name: Get process needed for {{ plugin_name.key }}
  shell: "pgrep -c {{ plugin_name.value.cmd }}"
  register: get_process
  failed_when: get_process.stdout == ""
  changed_when: false
  when: by_process == true and plugin_name.value.cmd is defined

- name: Get file needed for {{ plugin_name.key }}
  stat:
    path: "{{ plugin_name.value.path }}"
  register: get_file
  changed_when: false
  when: by_files == true and plugin_name.value.path is defined

- name: Add {{ plugin_name.key }} to needed plugins
  set_fact:
    CMK_PLUGINS: "{{ CMK_PLUGINS + [ plugin_name.key ] }}"
  when: (get_process.rc is defined and get_process.rc == 0) or
        (get_file.stat is defined and get_file.stat.exists == true) or
        (by_package == true and plugin_name.value.pkg is defined and plugin_name.value.pkg in packages) or
        (plugin_name.value.force is defined and plugin_name.value.force == true)
