---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu2204
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    systemd: always
  - name: ubuntu2404
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    systemd: always
  - name: debian11
    image: docker.io/geerlingguy/docker-debian11-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    systemd: always
  - name: debian12
    image: docker.io/geerlingguy/docker-debian12-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    systemd: always
  - name: rockylinux9
    image: docker.io/geerlingguy/docker-rockylinux9-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    systemd: always
provisioner:
  name: ansible
  connection_options:
    ansible_connection: podman
  config_options:
    defaults:
      roles_path: "$MOLECULE_PROJECT_DIRECTORY/.."
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
  create_sequence:
    - create
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
