# Written by Checkmk store (actually Ansible)

agent_signature_keys.update({1: {'alias': 'ansible_collection',
     'certificate': '-----BEGIN CERTIFICATE-----\n'
                    'MIIC7jCCAdYCAQEwDQYJKoZIhvcNAQEFBQAwPDEnMCUGA1UECgweQ2hlY2tfTUsg\n'
                    'U2l0ZSBrb2NoYmFja2tvY2hiYWNrMREwDwYDVQQDDAhjbWthZG1pbjAgFw0yNDA0\n'
                    'MTAxMjA4MjdaGA8yMDU0MDQwMzEyMDgyN1owPDEnMCUGA1UECgweQ2hlY2tfTUsg\n'
                    'U2l0ZSBrb2NoYmFja2tvY2hiYWNrMREwDwYDVQQDDAhjbWthZG1pbjCCASIwDQYJ\n'
                    'KoZIhvcNAQEBBQADggEPADCCAQoCggEBALkWEToPVSC8ibmNqhgTnN9WozwIb4pi\n'
                    'gsrEnhzGC/GW65aJBe+yUlAtVd+PBnTfUwG+ibA2pZ7Bcc+M4FDx/87631ms4EVZ\n'
                    'KGeAWrDvxgJsMYWb0O2M0HWuAWnCV2xeu5yIcE+XbPhoxVsxMDUsy2uJVgNMvSIS\n'
                    'mV+POBBjJAEFQSCibL8nNzlRU6gNXhPk49xxs2daUfpL17gO2laywux8UtFJqE21\n'
                    'v+86Z4MQjDxYxpNUC9/sHHCJ97alMPJa7XJLOAUCPjHH7UWorhKCyIkzA03TIj46\n'
                    'Cgg2qrclh/4hnBzm5+NrdW02Wm62FHPiz1Z5L9UtYs2OvYX3XeEdGY0CAwEAATAN\n'
                    'BgkqhkiG9w0BAQUFAAOCAQEARHLoPwMC9o1fDSAQSYfaTE09RtsrpOTXBmaNqpYR\n'
                    'PWqtA5Uz0X7+LEnkMrTkQZ7gI6FQ6PItFcE4W+AkXZLK3JmJIcktJlKoDIQwdXV6\n'
                    'DrJgDAIHc7UnSDkgeTYegnQoNmT3Q6uZUm2yaK4AgN0fEEtg3HYgw4ltc2KaqQM8\n'
                    'vtlEamGx85gCNUGPugJaP71FoE+t1qi0dGFQ+RUcHUBHlhrMzAd80K+Ctp8uKIs/\n'
                    'Zu3h3eprE6JKPNqIdg38qGMlkI2RS9ZDFMIm4CDLp+10ZDPr0Muuvk03v82s2Tjd\n'
                    'NVxXHH881oAVucR4LHX3C8YwQW7ryrSOngKBl35gmOIq+A==\n'
                    '-----END CERTIFICATE-----\n',
     'date': 1712750907.4960656,
     'owner': 'cmkadmin',
     'private_key': '-----BEGIN ENCRYPTED PRIVATE KEY-----\n'
                    'MIIFLTBXBgkqhkiG9w0BBQ0wSjApBgkqhkiG9w0BBQwwHAQIgozcjYS2N2wCAggA\n'
                    'MAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBB/AJDeg9Ovz9WFEiIU7M/xBIIE\n'
                    '0HwKBbznuz3iKq2PU/pPkx/2RmjmZJ++TLjtpznhTphHvg9kJ9HLgDPquAniLoGu\n'
                    'tpEUa8fjBb7tkg/abznP/PCjRA3eAobGkfir+t0Iqk165V7wc+ePhukKGWiOzSQa\n'
                    'TEqKKQSPKPEyJCbOFtGXb3YiqfhHwmiAdMTH3GkfprfesOqS5ooCCW7kMpnYeB2z\n'
                    'tIx62fHXz6/338v0X6OTEZryYoVPyvFijYXGix6/wlj1BdMtuk2LLCCdfHUsZmDU\n'
                    'tcWfTIp/kibJXJ4Ss4EsaT/d02s3ZegBeY9hgq2n4oe99yje67iGMPdSTqVNkToe\n'
                    'aLf0RWwz1Rb6X2Ha4oN/xyKd+Duw4ikqa+hhq6pNs4ycOLaCFSFd3FaESCt/dzmL\n'
                    '3JWpuvBaSySGrimS5/ZXolMKu/kNPv0S6LfWHnJS/NFuNzw6nWBb2d15LpJDZFC3\n'
                    '0L/p3hUNUOn1hEu0+GFmMiKQCStKArC49HNvS7ZqAAVVGjQ+fJBb8EYRUIlR6UJU\n'
                    'i9LyhRrdNhP1IUM3dMOWCPKIgC3jArGF9ZOSginn9bv5ghkalWVvz3JGhjl+g+jU\n'
                    'fKeX/B61DCqDCYxrjM5RsPUybLkleOCfFa1n1cRumJpOAvi3nIf0hwiVq1HgV5wQ\n'
                    '6jmrJB8rUdiHLNCbC/smeQKzHlC5w0XXCBJTCpKL5v8esOzs8NtQxE9NfyF2343I\n'
                    '92Ns6GGz96Anem1XHKfnoPvitbKtb5KIfPq0ffFPFu5xzhC0GZWNowdXrlR/PJ+E\n'
                    '+3COntBBgtWysL+Cf7yCFv7M9vCNnrRkaE3X55sbPLET7KKW4pCk9qCuL0je3hya\n'
                    'pJ/TTzxckuTC52uuaU0GmWyWgxUnNRObSI8yU4MBqC/e2nkURMdYpR6IaqzoH+O1\n'
                    '2AiQytx+yZpia7ndvi25Sao56ZSi8KPZx/DUFX2r4REjtibGxYbbyY9xHfNWg//l\n'
                    '5iEPBhCLk4xaofVz4NH59ubTO2G9+gQ6FPQ2vi07i1csCzBOcQIWLvXzetRvczvn\n'
                    'TeRFc9dDBUAOBSdSuw0x1MagfRTKto2ASPSELYcQGJJvWVso3y4V0uGBziv9gbbR\n'
                    'V2ZpSvqbpI3zojr7okwpDv72PcgmBChkQ1EugyW4N0qLxUVv+NhuHC11qNGGSWvp\n'
                    '1w3e3kFZ+ggdWZCxbvmV9YVSkdVw3KlOFWPXQPdk5et5wnEFrTxPTC+HG4MKs5SY\n'
                    'fvB1/X3HN2qD684Q0xgOjkQoWoCQGlr4rwCvytbE9OQDwzPlvrA7isBrYwYA1Q0S\n'
                    'XzpU9CJO2t4i4ONi2R6RQQYFMejTZ9g3p9rEw6xfxN3073rTJnkbzMDF5zS2Qj/X\n'
                    '6aVJw/322nTQcNEGl8RtY+0jRisAbch9JJPNIcXZRHDWMFroCbtScVsTPJKie9yR\n'
                    'A3gDoR4pJMJ+tgSpADfFAAg1KfG9VGRERULkwFHZCt+micNASqU88jVaxHK6U29D\n'
                    'MXq6z0//07wWpeR39yA+i3s462fLDgs3tqp0FoVVf9Wbur3FhOjsDAkV1yh/uK9e\n'
                    'UAf69KPWfTH5awkmpM0Yz76qV+L4B/QczQKWPtUzlRJxvAeKGfHkD1UIPkMUPmQQ\n'
                    'fNw0rolGI0G47R2/78ouGbsySM+FPZNkMMI/YIEN0f4Y\n'
                    '-----END ENCRYPTED PRIVATE KEY-----\n'}})

