# Written by Checkmk store (actually Ansible)

agent_signature_keys.update({1: {'alias': 'test_key',
     'certificate': '-----BEGIN CERTIFICATE-----\n'
                    'MIIFUzCCAzugAwIBAgIUH/fvbU7RLhm6METjrUvx/Xhr4cMwDQYJKoZIhvcNAQEN\n'
                    'BQAwQzERMA8GA1UEAwwIdGVzdF9rZXkxGzAZBgNVBAoMEkNoZWNrbWsgU2l0ZSBs\n'
                    'b2NhbDERMA8GA1UECwwIY21rYWRtaW4wHhcNMjMwNTE2MTI1MzUyWhcNMjUwNTE2\n'
                    'MTI1MzUyWjBDMREwDwYDVQQDDAh0ZXN0X2tleTEbMBkGA1UECgwSQ2hlY2ttayBT\n'
                    'aXRlIGxvY2FsMREwDwYDVQQLDAhjbWthZG1pbjCCAiIwDQYJKoZIhvcNAQEBBQAD\n'
                    'ggIPADCCAgoCggIBAKxdBrzxkAeUGBDjio6l2q9Q1NhK8xWAnH/Lo+eIDWu3Gy8j\n'
                    'Wnlnfj2He5uWHZ1aIE90sGDZbd51G75Uc0UM2APkhq6iOVn8VZdxIJ5fUsfB1NMM\n'
                    'qizaiLIe5Yl9lQD1ffYRrOWF2cPg0rifEZtqawB2umTiRMlATG8PNAsF2coTuYzh\n'
                    'iNVJUySYT256MKN6ybut5AWaHO+Oka5IknknW4q7dNjStxIgi7BybunTGzvKCjY6\n'
                    'LRKMQtxvhu3pxgmwJ8J20gbuXs+pt7isMzvGrBGavvCHMgNZfGeLlGvnx5ScvrOO\n'
                    'AFpbeQd4fVbs0Vi31v1V3ufpazA/D//Y3K7byUUGB5dg1mBM4AMW1y0Q+Mk9LQYD\n'
                    'gHRJ5THwFdx8+NkeoIX9PDVGUxVsiNwJ6wp1rCJ7T+J351svGvKuY7nZflwfxRzQ\n'
                    'j549ZUJG3SMAeh6lSmPXNgMK5gIpKSXNukxaB6gepsGtDpdMHxlR4ulnUGs/29u/\n'
                    'Qh7YCabrzJRsdys/MiwnDLJCPlVwnb2tZTVwZMekCL16hQEbWGPA5AvKbaM8KyaL\n'
                    '/rV7jQaZESgvfFBxsoFq1ZKIvX9Q/pJvM9DgU1vjIV0E5b9zbk4mdbEBJ+oArV+0\n'
                    'jrCVJZilfLF0xxQZ7kP9SCi2u3s+sc9BNlyehae3ykkz267LkyGc6QyfFws9AgMB\n'
                    'AAGjPzA9MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFCa8C1f2XP3tRnmbFB4AUB2G\n'
                    '88BrMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQ0FAAOCAgEAWlBudYWDj9+q\n'
                    'qsERE3DL7yKSKVE5sJbSCkJ4ZxUtuCI6tXe+vykBTh4c++uizen6vX8NG9WnuGDx\n'
                    'Wo1zjHuiQCduorMMuwKnqV+VUgnSk6BF6YnUxE4rnw9t6Rp+GK+2FDYTAi6CXx/v\n'
                    'hzxxSefdx67J5hLpLtgCFcwLJe+uf26OvQNTMmgiHDHas07cNKh6At68DCZNmkau\n'
                    'PETrrwCHVt75OopAfydejp+u0j/nig3/lyflpDKxjXh6h4uhoGRa4QFQUETyYYrw\n'
                    'sgalhk1SopLL65uP0KxZjEkbVBhuIX/x5lCGtuNJt9cFLFACkkjvLEw1+5GtNTNk\n'
                    '7rBr5Q+P5lqbsIqckcms2Pecqy/KmF1+FY1f5TnfrlyQ/6I1/XyYaWJ8Bwz60uDN\n'
                    'deB0xq8Sikd5SkluhvmCl/FDu2T50fu5wAQ2Y/XHub1hdKCjbcRnw+1i3eUu7hso\n'
                    'KiVKYDNMzCAl1q0RPHHlUFfAx0uFBINRR6sGuu44CxLPTKPpXj+BZLWD9buPi8U6\n'
                    'vCYuRvdM6AvKJFuFo39CBDRwVFXyPYKgD8HWKczkrjIgvhrOk7pw2hGhmg1h5Bib\n'
                    'e23QLEM4wvLRvK4QWzAcJSTahuQVtiX6+Lt7g82aGm2oZXC1TeWPbsJD+od4D3yG\n'
                    'IcHJbqKvCxWBU+JbVqWifkxhiEX0kEM=\n'
                    '-----END CERTIFICATE-----\n',
     'date': 1684241632.3241942,
     'not_downloaded': True,
     'owner': 'cmkadmin',
     'private_key': '-----BEGIN ENCRYPTED PRIVATE KEY-----\n'
                    'MIIJrTBXBgkqhkiG9w0BBQ0wSjApBgkqhkiG9w0BBQwwHAQItIV9A8Gte68CAggA\n'
                    'MAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBBJRHrWeaU57vPhRR2X/vBhBIIJ\n'
                    'UCZbfLTKnffrE33AxBlOesWTBGjABZXB4vGGQGHqPvUyvf7FsP0kyiOnjN0hf3vw\n'
                    'Cdm/qhm0iN74iKaKAhsk87ZjBVs6Y3DhxtOQRxuWKmZieJcrsMBfDMKVl/jQ/3g0\n'
                    'vg1Ac92atqmZLqNZWS5AMP7wTM/4crVYOVrgoE1FoNuX1Ik0Ku/E9HKEliH7jURY\n'
                    'x4zLvYpL8sS8lRT7B9jTEP0HOrMI9QCq8ddzSfztsz4ou6z0thpHfZ2M4pE9QTOO\n'
                    'dhC247QqhzhQRObSB58tse5SrONhue58VNnn2NFfNIxuhYRf8sqgVS0sl5TL2SIM\n'
                    'zG3pdNNksxZk5tVNe48t3VRFkBYZUckCxdGa+3iKsyFwZJD/FOIgUrEoFKkl6CLA\n'
                    'Guq8qn4r3UluvFAnGgbMKcSD943VKQdvrwP9gqjJG8f76qbCF5Rl9jeDDbPLs1Fg\n'
                    'fVRxj5fA/vt3byUi9dn890EdYEHxt8RacUDkGe6IytZu8IndO9uE6pxyijJWZbLW\n'
                    'wr4j6z1EcCoVnqgpok2MZMo0OQ5Srs9yzfottp3P+WILsZA2cgCFcuGjBYo0hrqh\n'
                    '0woORtVHusZsQdt6fkg/tWfaqcPrA6GKHn86YIfBG64pinnINCSAtAOju8lA6VH/\n'
                    'gb4KID2TpebZWiV24S57km5qGFwKFkf/6oq+UEfZc2cIuIMUq30oZR8WngNN3NUz\n'
                    'EMKHrtd1RudBffsTcihQhQqnbvStgdRl9gFgzlgx4VahUtKRQJd+fmqfIqJ5SEZG\n'
                    'eiwoKyUPPHkaIzuijkblG3Yvow4Vxh6UIJENX2w7Po5oGlCU0TLakXevSqDIL0+l\n'
                    'Bu8iYI63vEEd5WRiihfLg1kq/A4QxY1uX8iOP1Y/QacsW8R8a7mMp77rY4pjGrHs\n'
                    'GKXjQJF8T3DiGdIXTGaWjgzcEvb2n8vneNJQQQ1blRcvX0Ua63jMKOxC/E0E/cxa\n'
                    'UD7iXxHE3omeWQ7l/5rOO6eXltIDC74aYaJrJUolOxQo3hKPIKv2qshrE4rlmJSN\n'
                    '/nlzB8tD/KgX8p7j8dRvjOQum3VKiE9ZRsP3egty8kl+9Qgr0hXaRqPjQdmCi2UI\n'
                    'dy2cYnyFLMt8PfWUeBb1dBmudxAVYGn7pz7VKpy2K4CKO8alR5gC+YRBGSzy8qPE\n'
                    'yKL/gR1olnsr9Fb4GaBb0oPR/ndFHOs44v+wGt7yRM2LPwZpf/YU32CKD+Cq4K3J\n'
                    '/Y3Ug1vOE1D37YC9AMgwore0hXByxiGsI0eG06SJur+fF6xtzUsnT1ApPj6CHkQM\n'
                    'dL1ZNMjsp0JpnRa9MywcUzJkUEGPx/BTRvJp3EdzFj6HKUQVB/4+N/5zPxMRa3sJ\n'
                    'XXGL8/xHuAyQVVAdeKtCrJWZBLKiz0WCaoWTMkCZwRPmoEbswlgc4XHcLwCW7WOm\n'
                    '5ypo4coVaXLCLIiOBHeMSJfZBq+DkZoztSzUtEXKn1vurmggUk5s/XaQsrh94jKN\n'
                    'o5qDQWCJigctQrljNj5WNxpc++ux7qj9qC8Y1GSEhuWeigSevdB8JA4vaZH4kXnQ\n'
                    'zX9+3crSvsvEddmtW3GCwC08xp4mdxjEFJjQ6+L5gf9pJg8aqT9Wd/6pHtt7zS/C\n'
                    'OpaSnAz5pCFXA5Ip1WsxnrQwqMwU1iilIAWtKFcokwhUpLqtnd8qMOoCq+t2MiZq\n'
                    'VwQEeRJEJ8tKQjtEibwUIkZuBA4lQ9tFHBychlFsa93o2Glxtit8VFtssBK4sG4M\n'
                    'J5Wdwd6/6j27r2sKDnfqX68n56w8hqAlixV+74oTC9kEK/S9ROCExGNxBFHbxvW1\n'
                    'B56YBj4rbP6cyxq+mVmaddcB0oD3KZXx5xMU8AojyGiy0bhBqj4qmLDxO58tH6g4\n'
                    'e5vAeYcuaknSUTSkzbVgzcsn4d+iUxWJNouvsF1xT0+UDqT+Wf662cKqHCZwdfJU\n'
                    's8c2bgrg0P9W2T3tZ7xwkIcvBOPNDQZu32gO45ye3Ui8/9fp7Mw/81HEOBfeyNT6\n'
                    'SNSs6ZLVsfWxGClgzlEJP6Ul21VIY3lw6CkKDOzlJjSMkRBoFWz0Ffqwkz9wsJOe\n'
                    '9y+gEQIoBJwAUeIgOLyBq1bTYiis9TAePxpS4sh4H+ZNYrzMaDD+fTRkC1+dt17I\n'
                    'U+4OWZMOLB1sbonkfHM4yaBt8kjasUjorVuFTNmhHb4FDQgYvHpabM/lNJoz4EG1\n'
                    'cUnOk5YEj16XKIP3ICvkbopryhXgVlwPGfHJPgiicDA/Gs1hdusYz3Vfu1hu7MJ8\n'
                    'LQwrkDjfG0aS7efiMwMdrQA/JD3NbubvDzVSRmTfNbkU2NEcrXXADCkr9KBTDor+\n'
                    'xJGi/I2h7JBWQC88+VqzlivCZF+1ZLeZgtu3Sd1UtEHoXh+czfbMvW+HhRHFERim\n'
                    'CEu9kWAmejzNAUL3XpQqTXSCdW7igiHUau3F7UtY0SuAGOGebC0xhZQOUlAVxyq1\n'
                    'mbnSSv+MaKTKakYcmfK2djm+MVooL+GUkkFaDJDcP3NU9sSjt3whIvjxJG/JK001\n'
                    'KtDDdMzKDvO+GDjFCrzm7eeEFu8tpj0I/VN72VT3EtR5yN36xOSbaxI3TvS++htU\n'
                    'i3DzBxQ97h+CT8C9inCX+qYolBU6oV8b24BQIbNlcWmkci8xclg3SdUTbmPle0rd\n'
                    '3uHBfW8lKLc4FQalBIXeADfDH0XV3FU7WOVevcTQusWQr5S3F8dV6KLyIdsvHNRv\n'
                    'apOaxqo7VaetBdifqls6/+RuSvKgdNZNpb24bJpJrwJ7ctkHyVDsh2+R92+HKQ6U\n'
                    '+7zNeT8n5+IHTRJfWDApvgtDr318COUYO/8rRNvM8hQW5tC/Umods0ZZTlv71fkY\n'
                    'D73bZmoBQVwq9wEUJXymCSxwKBvIMWGdA4DrHtwAQ0buxCpktajhLzPAmbXos9Z7\n'
                    '6LJpC+aCcLO2cYNgZtGqiGhuG0WuquHWh4/76AJ58GoFBJstjMDYrwtHBfa/ciXj\n'
                    '4GetbLsfvFyg1+S+Fx7UBki5h1sTxWo5FvCiHazK02ARkSuj0nZp2HS+U7tEQr69\n'
                    'he9dEqeQiazhOC8PIIBeWEIc2AumbBsHkyrLaYoKxuCLj45NypGfFmCNzdB1IlU0\n'
                    'M3AeIoaCIqYApn/3yjwbJ3fw7sLPmXe+072ZS+MkDHjQz1B/fZtVvPgDH1xncmsP\n'
                    'jVEOrjjEvPgjxh5qTKcnRk7IDrVphN+yueD+C3RhE8Hb\n'
                    '-----END ENCRYPTED PRIVATE KEY-----\n'}})