---
- name: "Run roles."
  hosts: vagrant

  vars_files:
    - ./vars/config.yml

  tasks:

    - name: "Run server role."
      tags: [server]
      ansible.builtin.import_role:
        name: server

    - name: "Run agent role."
      tags: [agent]
      ansible.builtin.import_role:
        name: agent
