# Resources:
# - About reusable workflows: https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows
# - Template for this file: https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml
# - About Ansible integration tests: https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html

name: Template for Ansible Unit Tests

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      testpath:
        required: true
        type: string

jobs:

  units:
    runs-on: ubuntu-24.04
    name: Ⓐ${{ matrix.ansible }}+py${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {ansible: stable-2.16, python: '3.12', core: 'ansible-core~=2.16.0'}
          - {ansible: stable-2.19, python: '3.12', core: 'ansible-core~=2.19.0'}
          - {ansible: stable-2.19, python: '3.13', core: 'ansible-core~=2.19.0'}
          - {ansible: stable-2.20, python: '3.12', core: 'ansible-core~=2.20.0'}
          - {ansible: stable-2.20, python: '3.13', core: 'ansible-core~=2.20.0'}
          - {ansible: stable-2.20, python: '3.14', core: 'ansible-core~=2.20.0'}
          - {ansible: stable-2.21, python: '3.12', core: 'ansible-core~=2.21.0'}
          - {ansible: stable-2.21, python: '3.13', core: 'ansible-core~=2.21.0'}
          - {ansible: stable-2.21, python: '3.14', core: 'ansible-core~=2.21.0'}
          - {ansible: devel, python: '3.13', core: 'https://github.com/ansible/ansible/archive/devel.tar.gz'}

    steps:

      - name: "Check out code."
        uses: actions/checkout@v7
        with:
          path: ansible_collections/checkmk/general

      - name: "Install uv and set the python version."
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          github-token: ${{ github.token }}
          working-directory: ./ansible_collections/checkmk/general
          python-version: ${{ matrix.python }}

      - name: "Setup uv venv for: (${{ matrix.core }})."
        run: |
          echo "ANSIBLE_VENV=$RUNNER_TEMP/ansible-venv" >> "$GITHUB_ENV"
          uv venv --python '${{ matrix.python }}' "$RUNNER_TEMP/ansible-venv"
          uv pip install --python "$RUNNER_TEMP/ansible-venv" '${{ matrix.core }}'

      - name: "Run unit test."
        run: $ANSIBLE_VENV/bin/ansible-test units ${{ inputs.testpath}} -v --color --python ${{ matrix.python }} --docker default
        working-directory: ./ansible_collections/checkmk/general
