# https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml
# README FIRST
# 1. replace "NAMESPACE" and "COLLECTION_NAME" with the correct name in the env section (e.g. with 'community' and 'mycollection')
# 2. If you don't have unit tests remove that section
# 3. If your collection depends on other collections ensure they are installed, see "Install collection dependencies"
# If you need help please ask in #ansible-community on the Libera.chat IRC network

name: Ansible Integration Tests for Roles
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel
    paths:
      - 'roles/**'

env:
  NAMESPACE: tribe29
  COLLECTION_NAME: checkmk 

jobs:

###
# Integration tests (RECOMMENDED)
#
# https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html


# If the application you are testing is available as a docker container and you want to test
# multiple versions see the following for an example:
# https://github.com/ansible-collections/community.zabbix/tree/master/.github/workflows

  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      ports:
          - 80:80
    name: I (Ubuntu+Ⓐ${{ matrix.ansible }})
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.12
          - stable-2.13
          - devel

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # it is just required to run that once as "ansible-test integration" in the docker image
          # will run on all python versions it supports.
          python-version: 3.9

      - name: Install prerequisites
        run: apt-get -y update && apt-get -y install python3-pip openssh-client

      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      # Run the integration tests
      - name: Run integration test
        run: ansible-test integration roles -v --color --retry-on-error --continue-on-error --diff
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

  debian:
    runs-on: ubuntu-latest
    container: 
      image: debian:bullseye
      ports:
          - 80:80
    name: I (Debian+Ⓐ${{ matrix.ansible }})
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.12
          - stable-2.13
          - devel

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # it is just required to run that once as "ansible-test integration" in the docker image
          # will run on all python versions it supports.
          python-version: 3.9

      - name: Install prerequisites
        run: apt-get -y update && apt-get -y install python3-pip openssh-client

      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      # Run the integration tests
      - name: Run integration test
        run: ansible-test integration roles -v --color --retry-on-error --continue-on-error --diff
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
