concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Lookup Module Bakery

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - main
      - devel
    types:
      - opened
    paths:
      - 'plugins/lookup/bakery.py'
  push:
    paths:
      - '.github/workflows/ans-int-test-lkp-bakery.yaml'
      - 'plugins/lookup/bakery.py'
      - 'plugins/module_utils/**'
      - 'tests/integration/files/includes/**'
      - 'tests/integration/targets/lookup_bakery/**'

jobs:

  integration:
    name: "Integration ${{ matrix.checkmk_version }}.${{ matrix.checkmk_edition }}"
    uses: ./.github/workflows/_template-ans-int-test.yaml
    with:
      module: lookup_bakery
      checkmk_version: ${{ matrix.checkmk_version }}
      checkmk_edition: ${{ matrix.checkmk_edition }}
    strategy:
      fail-fast: false
      matrix:
        checkmk_version:
          - 2.3.0p44
          - 2.4.0p23
          - 2.5.0-2026.03.18
        checkmk_edition:
          - managed
          - ultimatemt
        exclude:
          - checkmk_version: 2.3.0p44
            checkmk_edition: ultimatemt
          - checkmk_version: 2.4.0p23
            checkmk_edition: ultimatemt
          - checkmk_version: 2.5.0-2026.03.18
            checkmk_edition: managed
