concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Module Downtime

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - main
      - devel
    types:
      - opened
    paths:
      - 'plugins/modules/downtime.py'
  push:
    paths:
      - '.github/workflows/ans-int-test-downtime.yaml'
      - 'plugins/modules/downtime.py'
      - 'plugins/module_utils/**'
      - 'tests/integration/files/includes/**'
      - 'tests/integration/targets/downtime/**'

jobs:

  integration:
    name: "Integration ${{ matrix.checkmk_version }}.${{ matrix.checkmk_edition }}"
    uses: ./.github/workflows/_template-ans-int-test.yaml
    with:
      module: downtime
      checkmk_version: ${{ matrix.checkmk_version }}
      checkmk_edition: ${{ matrix.checkmk_edition }}
    strategy:
      fail-fast: false
      matrix:
        checkmk_version:
          - 2.3.0p45
          - 2.4.0p24
          - 2.5.0b1
        checkmk_edition:
          - raw
          - managed
          - community
          - ultimatemt
        exclude:
          - checkmk_version: 2.3.0p45
            checkmk_edition: community
          - checkmk_version: 2.3.0p45
            checkmk_edition: ultimatemt
          - checkmk_version: 2.4.0p24
            checkmk_edition: community
          - checkmk_version: 2.4.0p24
            checkmk_edition: ultimatemt
          - checkmk_version: 2.5.0b1
            checkmk_edition: raw
          - checkmk_version: 2.5.0b1
            checkmk_edition: managed
