concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Module Role Unit Tests

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - main
      - devel
    paths:
      - 'plugins/modules/role.py'
  push:
    paths:
      - '.github/workflows/ans-unit-test-role.yaml'
      - 'plugins/modules/role.py'
      - 'plugins/module_utils/**'
      - 'tests/unit/plugins/module_utils/**'
      - 'tests/unit/plugins/modules/test_role.py'

jobs:

  integration:
    name: "Unit Tests"
    uses: ./.github/workflows/_template-ans-unit-test.yaml
    with:
      testpath: tests/unit/plugins/modules/test_role.py
