concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Module Host

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - main
      - devel
    types:
      - opened
    paths:
      - 'plugins/modules/host.py'
  push:
    paths:
      - '.github/workflows/ans-int-test-host.yaml'
      - 'plugins/modules/host.py'
      - 'plugins/module_utils/**'
      - 'tests/integration/files/includes/**'
      - 'tests/integration/targets/host/**'

jobs:

  integration:
    name: "Integration ${{ matrix.checkmk_version }}.${{ matrix.checkmk_edition }}"
    uses: ./.github/workflows/_template-ans-int-test.yaml
    with:
      module: host
      checkmk_version: ${{ matrix.checkmk_version }}
      checkmk_edition: ${{ matrix.checkmk_edition }}
    strategy:
      fail-fast: false
      matrix:
        checkmk_version:
          - 2.3.0p42
          - 2.4.0p22
          # - 2.5.0-2025.02.24
        checkmk_edition:
          - raw
          - managed
