# README:
# - When changing the module name, it needs to be changed in 'env:MODULE_NAME' and in 'on:pull_requests:path'!
#
# Resources:
# - Template for this file: https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml
# - About Ansible integration tests: https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html

env:
  NAMESPACE: checkmk
  COLLECTION_NAME: general
  MODULE_NAME: user

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Ansible Integration Tests for User Module
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - main
      - devel
    paths:
      - 'plugins/modules/user.py'
  push:
    paths:
      - '.github/workflows/ans-int-test-user.yaml'
      - 'plugins/modules/user.py'
      - 'tests/integration/files/includes/'
      - 'tests/integration/targets/user/'

jobs:

  integration:
    runs-on: ubuntu-24.04
    name: Ⓐ${{ matrix.ansible }}+py${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.16
          - stable-2.17
          - stable-2.18
          - devel
        python:
          - '3.10'
          - '3.11'
          - '3.12'
        exclude:
          # Exclude unsupported sets.
          - ansible: stable-2.18
            python: '3.10'
          - ansible: devel
            python: '3.10'
          - ansible: devel
            python: '3.11'

    services:
      ancient_cre:
        image: checkmk/check-mk-raw:2.2.0p45
        ports:
          - 5022:5000
        env:
          CMK_SITE_ID: "ancient_cre"
          CMK_PASSWORD: "Sup3rSec4et!"
      old_cre:
        image: checkmk/check-mk-raw:2.3.0p35
        ports:
          - 5023:5000
        env:
          CMK_SITE_ID: "old_cre"
          CMK_PASSWORD: "Sup3rSec4et!"
      old_cme:
        image: checkmk/check-mk-managed:2.3.0p35
        ports:
          - 5323:5000
        env:
          CMK_SITE_ID: "old_cme"
          CMK_PASSWORD: "Sup3rSec4et!"
      stable_cre:
        image: checkmk/check-mk-raw:2.4.0p9
        ports:
          - 5024:5000
        env:
          CMK_SITE_ID: "stable_cre"
          CMK_PASSWORD: "Sup3rSec4et!"
      stable_cme:
        image: checkmk/check-mk-managed:2.4.0p9
        ports:
          - 5324:5000
        env:
          CMK_SITE_ID: "stable_cme"
          CMK_PASSWORD: "Sup3rSec4et!"

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: "Install uv and set the python version."
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python }}
          enable-cache: true
          working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/

      - name: "Setup uv venv."
        run: uv venv
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Install ansible-base (${{ matrix.ansible }})
        run: uv pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Run integration test
        run: uv run ansible-test integration ${{env.MODULE_NAME}} -v --color --continue-on-error --diff --python ${{ matrix.python }}
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
