# README:
# Resources:
# - Template for this file: https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml
# - About Ansible sanity tests: https://docs.ansible.com/ansible/latest/dev_guide/testing_sanity.html

name: Ansible Sanity

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*'
      - 'docs/**'
      - 'changelogs/**'
      - '**.md'
      - '**.rst'
      - 'roles/**'
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*'
      - 'docs/**'
      - 'changelogs/**'
      - '**.md'
      - '**.rst'
      - 'roles/**'

jobs:

  sanity:
    runs-on: ubuntu-24.04
    name: (Ⓐ${{ matrix.ansible }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - {ansible: stable-2.16, python: '3.12', core: 'ansible-core~=2.16.0'}
          - {ansible: stable-2.17, python: '3.12', core: 'ansible-core~=2.17.0'}
          - {ansible: stable-2.18, python: '3.13', core: 'ansible-core~=2.18.0'}
          - {ansible: stable-2.19, python: '3.13', core: 'ansible-core~=2.19.0'}
          - {ansible: stable-2.20, python: '3.13', core: 'ansible-core~=2.20.0'}
          - {ansible: stable-2.21, python: '3.13', core: 'ansible-core~=2.21.0'}
          - {ansible: devel, python: '3.13', core: 'https://github.com/ansible/ansible/archive/devel.tar.gz'}

    steps:

      - name: Check out code
        uses: actions/checkout@v7
        with:
          path: ansible_collections/checkmk/general

      - name: "Install uv and set the python version."
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          github-token: ${{ github.token }}
          working-directory: ./ansible_collections/checkmk/general
          python-version: ${{ matrix.python }}

      - name: "Setup uv venv for: (${{ matrix.core }})."
        run: |
          echo "ANSIBLE_VENV=$RUNNER_TEMP/ansible-venv" >> "$GITHUB_ENV"
          uv venv --python '${{ matrix.python }}' "$RUNNER_TEMP/ansible-venv"
          uv pip install --python "$RUNNER_TEMP/ansible-venv" '${{ matrix.core }}'

      - name: Run sanity tests
        run: $ANSIBLE_VENV/bin/ansible-test sanity --docker -v --color --coverage
        working-directory: ./ansible_collections/checkmk/general
