name: "Label Pull Requests."
on:
  pull_request_target:
    paths:
      - '.github/labels-prs.yml'
      - '.github/workflows/label-prs.yaml'
      - 'changelogs/**'
      - 'docs/**'
      - 'plugins/**'
      - 'roles/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-24.04
    steps:
    - name: "Label Pull Requests."
      uses: actions/labeler@v6
      with:
        configuration-path: .github/labels-prs.yml
        sync-labels: false
